/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.hutkovich.shakealert

import com.hutkovich.shakealert.main.Main

class App {
    val greeting: String
        get() {
            return "I'm alive!"
        }
}

fun main(args: Array<String>) {
    Main.main(args)
    println(App().greeting)
}
